### ISSUE TITLE
[APERO] allow SCIENCE_TARGETS not to be from obj database

### ISSUE THREAD

**Issue by njcuk9999** [njcuk9999/apero-utils#269]
See https://github.com/njcuk9999/apero-drs/issues/780

**Comment by alexandrineLH** [comment]
I got this error on three targets (GJ3090,  WASP90,  GJ729) for the HE reduction of 2024-09-12. GJ3090 and GJ729 are known targets. WASP90 was not in the database so I added it.

Here is the error message in full
```
00:25:56.802-  |PROC| ***************************************************************************
00:25:56.811-  |PROC| *
00:25:56.812-  |PROC| *  NIRPS_HE @PID-00017261871546586230-ND84 (V0.7.290)
00:25:56.812-  |PROC| *           py3.9.19  git:v0.7.290-stable-test
00:25:56.813-  |PROC| *
00:25:56.821-  |PROC| ***************************************************************************
00:25:56.829-**|PROC|I[40-001-00006]: DRS Setup:
00:25:56.837-**|PROC|I[
00:25:56.837-**|PROC|	DRS_ROOT: /cosmos99/nirps/git-bin/apero-drs-online/apero]: 
00:25:56.838-**|PROC|	DRS_ROOT: /cosmos99/nirps/git-bin/apero-drs-online/apero
00:25:56.839-**|PROC|	DRS_DATA_RAW: /cosmos99/nirps/apero-data/nirps_he_online/raw
00:25:56.840-**|PROC|	DRS_DATA_REDUC: /cosmos99/nirps/apero-data/nirps_he_online/red
00:25:56.841-**|PROC|	DRS_DATA_WORKING: /cosmos99/nirps/apero-data/nirps_he_online/tmp
00:25:56.842-**|PROC|	DRS_CALIB_DB: /cosmos99/nirps/apero-data/nirps_he_online/calib
00:25:56.842-**|PROC|	DRS_TELLU_DB: /cosmos99/nirps/apero-data/nirps_he_online/tellu
00:25:56.843-**|PROC|	DRS_DATA_ASSETS: /cosmos99/nirps/apero-data/nirps_he_online/asset
00:25:56.844-**|PROC|	DRS_DATA_OUT: /cosmos99/nirps/apero-data/nirps_he_online/out
00:25:56.845-**|PROC|	DRS_DATA_MSG: /cosmos99/nirps/apero-data/nirps_he_online/msg
00:25:56.846-**|PROC|	DRS_DATA_RUN: /cosmos99/nirps/apero-data/nirps_he_online/run
00:25:56.847-**|PROC|	DRS_DATA_PLOT: /cosmos99/nirps/apero-data/nirps_he_online/plot
00:25:56.848-**|PROC|	DRS_DATA_OTHER: /cosmos99/nirps/apero-data/nirps_he_online/other
00:25:56.848-**|PROC|	LBL_PATH: /cosmos99/nirps/apero-data/nirps_he_online/lbl
00:25:56.849-**|PROC|	DRS_CONFIG: /cosmos99/nirps/apero-settings/nirps_he_online/user_config.ini
00:25:56.850-**|PROC|	DRS_CONFIG: /cosmos99/nirps/apero-settings/nirps_he_online/user_constants.ini
00:25:56.851-**|PROC|	DRS_CONFIG: apero.constants.default.default_config
00:25:56.852-**|PROC|	DRS_CONFIG: apero.constants.default.default_keywords
00:25:56.853-**|PROC|	DRS_CONFIG: config.instruments.nirps_he.default_config.py
00:25:56.854-**|PROC|	DRS_CONFIG: config.instruments.nirps_he.default_keywords.py
00:25:56.855-**|PROC|	DRS_CONFIG: core.instruments.default.default_constants.py
00:25:56.856-**|PROC|	DRS_CONFIG: core.instruments.nirps_he.default_constants.py
00:25:56.857-**|PROC|	DATABASE: MYSQL
00:25:56.858-**|PROC|	DATABASE-calib: nirps@rali:calib_nirps_he_online_db
00:25:56.858-**|PROC|	DATABASE-tellu: nirps@rali:tellu_nirps_he_online_db
00:25:56.859-**|PROC|	DATABASE-findex: nirps@rali:findex_nirps_he_online_db
00:25:56.860-**|PROC|	DATABASE-log: nirps@rali:log_nirps_he_online_db
00:25:56.861-**|PROC|	DATABASE-astrom: nirps@rali:astrom_nirps_he_online_db
00:25:56.862-**|PROC|	DATABASE-lang: nirps@rali:lang_nirps_he_online_db
00:25:56.863-**|PROC|	DATABASE-reject: nirps@rali:reject_nirps_he_online_db
00:25:56.864-**|PROC|	PRINT_LEVEL: all
00:25:56.865-**|PROC|	LOG_LEVEL: all
00:25:56.866-**|PROC|	DRS_PLOT: 0
00:25:56.874-  |PROC| ***************************************************************************
00:25:58.449-  |PROC|A[40-001-00010]:  System information
00:25:58.450-  |PROC| ***************************************************************************
00:25:58.451-  |PROC|	 Python version = '3.9.19'
00:25:58.451-  |PROC|	 Distribution date = 'main, Mar 21 2024, 17:11:28'
00:25:58.452-  |PROC|	 Other information = 'GCC 11.2.0'
00:25:58.453-  |PROC|	 Path = '/cosmos99/nirps/bin/miniconda3/envs/apero-env-07/bin/python'
00:25:58.454-  |PROC|	 Platform = 'linux'
00:25:58.455-  |PROC| Currently installed python modules:
00:25:58.456-  |PROC|	astropy: 5.3  (req==5.3)
00:25:58.457-  |PROC|	astroquery: 0.4.6  (req==0.4.6)
00:25:58.458-  |PROC|	barycorrpy: 0.4.4  (req==0.4.4)
00:25:58.458-  |PROC|	duckdb: 0.8.0  (req==0.8)
00:25:58.459-  |PROC|	matplotlib: 3.7.1  (req==3.7.1)
00:25:58.460-  |PROC|	numba: 0.57.0  (req==0.57.0)
00:25:58.461-  |PROC|	numexpr: 2.8.4  (req==2.8.4)
00:25:58.462-  |PROC|	numpy: 1.24.3  (req==1.24.3)
00:25:58.463-  |PROC|	pandas: 2.0.2  (req==2.0.2)
00:25:58.464-  |PROC|	pandastable: 0.13.1  (req==0.13.1)
00:25:58.465-  |PROC|	psutil: 5.9.4  (req==5.9.4)
00:25:58.465-  |PROC|	scipy: 1.10.0  (req==1.10.0)
00:25:58.466-  |PROC|	tqdm: 4.65.0  (req==4.65.0)
00:25:58.467-  |PROC|	yagmail: 0.15.293  (req==0.15.293)
00:25:58.468-  |PROC|	lbl: 0.63.007 (git+https://github.com/njcuk9999/lbl.git)
00:25:58.469-  |PROC| Raw arguments used:
00:25:58.470-  |PROC|	 Arg 1 = '/cosmos99/nirps/git-bin/apero-drs-online/tools/bin/apero_processing.py'
00:25:58.471-  |PROC|	 Arg 2 = 'science_run_20240912.ini'
00:25:58.472-  |PROC| ***************************************************************************
00:25:58.480-**|PROC|I[40-001-00017]: Arguments used:
00:25:58.488-**|PROC|
00:25:58.488-**|PROC|	--RUNFILE: science_run_20240912.ini
00:25:58.496-  |PROC| ***************************************************************************
00:25:58.584-  |PROC|A[10-503-00005]: Key = REF_OBS_DIR not found in run file using default value (None)
00:25:58.593-  |PROC|A[10-503-00005]: Key = UPDATE_REJECT_DATABASE not found in run file using default value (True)
00:25:58.601-  |PROC|A[10-503-00005]: Key = UPDATE_FILEINDEX_DATABASE not found in run file using default value (True)
00:25:58.610-  |PROC|A[10-503-00005]: Key = UPDATE_IDATABASE_NAMES not found in run file using default value (All)
00:25:58.624-**|PROC|I[40-503-00046]: Updating reject database (from google sheets)
00:25:59.774-  |PROC|A[40-503-00044]: Updating index database with new raw files
00:26:10.031-  |PROC|A[40-001-00033]: 	Searching all directories
00:26:12.996-  |PROC|A[40-503-00044]: Updating index database with new tmp files
00:26:23.190-  |PROC|A[40-001-00033]: 	Searching all directories
00:26:25.033-  |PROC|A[40-503-00044]: Updating index database with new red files
00:27:41.940-  |PROC|A[40-001-00033]: 	Searching all directories
00:28:51.273-  |PROC|A[40-503-00044]: Updating index database with new out files
00:29:03.987-  |PROC|A[40-001-00033]: 	Searching all directories
00:29:12.185-  |PROC|A[40-503-00043]: Updating database with header fixes
00:29:12.804-  |PROC|A[90-503-00017]: Generating skip table
00:29:20.802-  |PROC|A[90-503-00018]: 	Found 176769 previous recipe runs
00:29:20.830-**|PROC|I[40-503-00011]: Generating run list
00:29:20.850-  |PROC|A[40-503-00035]: Calculating which nights have no object files
00:29:21.661-@$|PROC|W[10-503-00014]: Remove Engineering Nights: Directory 2022-11-05, 2022-11-06, 2022-11-07, 2022-11-08, 2022-11-09, 2022-11-10, 2022-11-11, 2022-11-12, 2022-11-13, 2022-11-14, 2022-11-15, 2022-11-16, 2022-11-17, 2022-11-19, 2022-11-20, 2022-11-21, 2022-11-22, 2022-11-23, 2022-11-24, 2022-11-25, 2022-11-29, 2022-12-09, 2022-12-10, 2022-12-11, 2022-12-19, 2023-01-12, 2023-01-13, 2023-01-14, 2023-01-15, 2023-01-28, 2023-01-30, 2023-01-31, 2023-02-01, 2023-02-02, 2023-02-03, 2023-02-05, 2023-02-06, 2023-02-09, 2023-02-14, 2023-02-15, 2023-02-16, 2023-02-28, 2023-03-12, 2023-03-13, 2023-03-14, 2023-03-16, 2023-03-18, 2023-03-19, 2023-03-20, 2023-03-21, 2023-03-22, 2023-03-23, 2023-03-24, 2023-03-26, 2023-03-27, 2023-03-28, 2023-03-29, 2023-03-30, 2023-03-31, 2023-04-20, 2023-04-21, 2023-04-23, 2023-04-26, 2023-04-27, 2023-05-10, 2023-05-11, 2023-05-12, 2023-05-14, 2023-05-15, 2023-05-16, 2023-05-18, 2023-05-21, 2023-05-25, 2023-05-26, 2023-05-27, 2023-05-28, 2023-06-09, 2023-06-10, 2023-06-12, 2023-06-13, 2023-06-14, 2023-06-16, 2023-06-17, 2023-06-18, 2023-06-19, 2023-06-21, 2023-06-22, 2023-06-28, 2023-06-30, 2023-07-01, 2023-07-02, 2023-07-03, 2023-07-04, 2023-07-06, 2023-07-07, 2023-07-09, 2023-07-10, 2023-07-11, 2023-07-12, 2023-07-13, 2023-07-15, 2023-07-18, 2023-07-20, 2023-07-26, 2023-07-31, 2023-08-06, 2023-08-07, 2023-08-09, 2023-08-15, 2023-08-17, 2023-08-18, 2023-08-19, 2023-09-01, 2023-09-02, 2023-09-05, 2023-09-07, 2023-09-09, 2023-09-10, 2023-09-11, 2023-09-19, 2023-09-26, 2023-09-30, 2023-10-01, 2023-10-02, 2023-10-06, 2023-10-15, 2023-10-16, 2023-10-17, 2023-10-21, 2023-10-22, 2023-10-28, 2023-10-31, 2023-11-08, 2023-11-09, 2023-11-17, 2023-11-30, 2023-12-01, 2023-12-02, 2023-12-09, 2023-12-18, 2023-12-25, 2023-12-26, 2023-12-27, 2023-12-28, 2024-01-01, 2024-01-02, 2024-01-03, 2024-01-04, 2024-01-05, 2024-01-06, 2024-01-07, 2024-01-08, 2024-01-09, 2024-01-10, 2024-01-14, 2024-01-22, 2024-02-08, 2024-02-13, 2024-02-18, 2024-02-19, 2024-02-20, 2024-02-22, 2024-02-23, 2024-03-26, 2024-03-31, 2024-04-12, 2024-04-13, 2024-04-14, 2024-04-16, 2024-04-21, 2024-04-25, 2024-04-28, 2024-04-29, 2024-04-30, 2024-05-07, 2024-05-10, 2024-05-13, 2024-05-14, 2024-05-15, 2024-05-16, 2024-05-20, 2024-06-03, 2024-06-07, 2024-06-11, 2024-06-12, 2024-06-13, 2024-06-14, 2024-06-17, 2024-06-18, 2024-06-19, 2024-06-20, 2024-06-21, 2024-06-22, 2024-06-27, 2024-07-05, 2024-07-08, 2024-07-11, 2024-07-12, 2024-07-13, 2024-07-14, 2024-07-16, 2024-07-18, 2024-07-19, 2024-07-20, 2024-07-30, 2024-07-31, 2024-08-01, 2024-08-02, 2024-08-03, 2024-08-06, 2024-08-14, 2024-08-15, 2024-08-16, 2024-08-17, 2024-08-19, 2024-08-26, 2024-08-27, 2024-08-28, 2024-08-29, 2024-08-30, 2024-08-31, 2024-09-01, 2024-09-02 was removed - no OBJECT type found. Set "ENGINEERING=True" to include this directory.
00:29:22.022-  |PROC|A[40-503-00036]: Adding condition for rejected odometer codes
00:29:23.377-@$|PROC|W[10-503-00023]: RECAL_TEMPLATES = False. Found 180 templates. Recipes requiring templates where templates were found will be skipped.
00:29:23.386-  |PROC|A[40-503-00014]: 	 Loading recipe module files...
00:29:23.746-**|PROC|I[40-503-00009]: Processing sequence 'PP_SEQ_OPT'
00:29:23.782-  |PROC|A[40-503-00038]: 	Adding recipe PPREF to sequence
00:29:23.820-  |PROC|A[40-503-00038]: 	Adding recipe PP_CAL to sequence
00:29:23.859-  |PROC|A[40-503-00038]: 	Adding recipe PP_SCI to sequence
00:29:23.897-  |PROC|A[40-503-00038]: 	Adding recipe PP_TEL to sequence
00:29:24.037-  |PROC|A[40-503-00038]: 	Adding recipe PP_HC1HC1 to sequence
00:29:24.076-  |PROC|A[40-503-00038]: 	Adding recipe PP_FPFP to sequence
00:29:24.114-  |PROC|A[40-503-00038]: 	Adding recipe PP_FF to sequence
00:29:24.152-  |PROC|A[40-503-00038]: 	Adding recipe PP_DFP to sequence
00:29:24.190-  |PROC|A[40-503-00038]: 	Adding recipe PP_SKY to sequence
00:29:24.229-  |PROC|A[40-503-00038]: 	Adding recipe PP_LFC to sequence
00:29:24.267-  |PROC|A[40-503-00038]: 	Adding recipe PP_LFCFP to sequence
00:29:24.305-  |PROC|A[40-503-00038]: 	Adding recipe PP_FPLFC to sequence
00:29:24.344-  |PROC|A[40-503-00038]: 	Adding recipe PP_FPHC1 to sequence
00:29:24.382-  |PROC|A[40-503-00038]: 	Adding recipe PP_HC1FP to sequence
00:29:24.420-  |PROC|A[40-503-00038]: 	Adding recipe PP_EVERY to sequence
00:29:25.378-**|PROC|I[40-503-00037]: processing recipes for 31248 raw data entries
00:29:25.387-  |PROC|A[40-503-00045]: 	 skipping recipe 'apero_pp_ref_nirps_he.py' (RUN_PPREF missing from ini file)
00:29:25.395-  |PROC|A[40-503-00021]: 	 skipping recipe 'apero_preprocess_nirps_he.py' (RUN_PP_CAL=False)
00:29:25.404-  |PROC|A[40-503-00012]: 	 processing recipe 'apero_preprocess_nirps_he.py' (PP_SCI)
00:29:27.390-!!|PROC|Could not find all objects in SCIENCE_TARGETS in astrometric database. Please check SCIENCE_TARGETS, add missing objects to astrometric database or remove from SCIENCE_TARGETS and try again. 
00:29:27.391-!!|PROC|	 objnames=GJ3090,  WASP90,  GJ729
00:29:27.414-!!|PROC|Traceback (most recent call last):
00:29:27.415-!!|PROC|  File "/cosmos99/nirps/git-bin/apero-drs-online/apero/core/utils/drs_startup.py", line 433, in run
00:29:27.416-!!|PROC|    llmain = func(recipe, params)
00:29:27.417-!!|PROC|  File "/cosmos99/nirps/git-bin/apero-drs-online/tools/bin/apero_processing.py", line 230, in __main__
00:29:27.418-!!|PROC|    raise e
00:29:27.419-!!|PROC|  File "/cosmos99/nirps/git-bin/apero-drs-online/tools/bin/apero_processing.py", line 166, in __main__
00:29:27.419-!!|PROC|    rlist = drs_processing.generate_run_list(params, findexdbm, runtable,
00:29:27.420-!!|PROC|  File "/cosmos99/nirps/git-bin/apero-drs-online/apero/tools/module/processing/drs_processing.py", line 938, in generate_run_list
00:29:27.421-!!|PROC|    newruns = _generate_run_from_sequence(params, sequence,
00:29:27.422-!!|PROC|  File "/cosmos99/nirps/git-bin/apero-drs-online/apero/tools/module/processing/drs_processing.py", line 1966, in _generate_run_from_sequence
00:29:27.423-!!|PROC|    filters = _get_filters(params, srecipe)
00:29:27.424-!!|PROC|  File "/cosmos99/nirps/git-bin/apero-drs-online/apero/tools/module/processing/drs_processing.py", line 3699, in _get_filters
00:29:27.425-!!|PROC|    WLOG(params, 'error', emsg.format(*eargs))
00:29:27.425-!!|PROC|  File "/cosmos99/nirps/git-bin/apero-drs-online/apero/core/core/drs_log.py", line 428, in __call__
00:29:27.426-!!|PROC|    raise drs_exceptions.LogExit(errorstring)
00:29:27.427-!!|PROC|apero.core.core.drs_exceptions.LogExit: Could not find all objects in SCIENCE_TARGETS in astrometric database. Please check SCIENCE_TARGETS, add missing objects to astrometric database or remove from SCIENCE_TARGETS and try again. 
00:29:27.428-!!|PROC|	 objnames=GJ3090,  WASP90,  GJ729
00:29:27.429-!!|PROC|
00:29:27.430-!!|PROC|
00:29:27.498-**|PROC| ***************************************************************************
00:29:27.507-@!|PROC|W[40-003-00005]: Recipe apero_processing has NOT been successfully completed
00:29:27.515-**|PROC| ***************************************************************************
```

**Comment by njcuk9999** [comment]
Actually, this was me running apero processing as a re-run and a typo (it was meant to be wasp80). There is no harm adding WASP90 to the database, so Ill leave it there!

**Comment by njcuk9999** [comment]
Actually the run file used here should be noted. For the manual trigger it will always be online_run.ini (this one was science_run_XXX.ini for example).
